### ISSUE TITLE
-Wsometimes-uninitialized warnings: variable 'r' is used uninitialized whenever switch case is taken

### ISSUE THREAD

**Issue by cpeterso** [kinetiknz/nestegg#46]
I see the following clang warnings when compiling Firefox with Xcode 8.3's clang version:

```
media/libnestegg/src/nestegg.c:1077:8 [-Wsometimes-uninitialized] variable 'r' is used uninitialized whenever switch case is taken
media/libnestegg/src/nestegg.c:1078:8 [-Wsometimes-uninitialized] variable 'r' is used uninitialized whenever switch case is taken
```

**Comment by kinetiknz** [comment]
We added a workaround for this in 4b0190a61203634cd474154edf52d433b02f34c8 and then removed it again in b74db1c7295ae155585a47606895d0a99268f1f4 because Clang's static analysis starting complaining about it, although restoring 4b0190a61203634cd474154edf52d433b02f34c8 doesn't cause it to complain locally now.
